### ISSUE TITLE
Trying to access "manage unit IDs list" for elements crashes the game

### ISSUE THREAD

**Issue by TonisGaming** [RAIDModding/BeardLib-Editor#5]
### Describe the bug

All elements that have a list to open up for units crashes the game, for example moveunit and unitsequence

The associated crash (this one happened with unitsequence)
[crash.txt](https://github.com/user-attachments/files/16602966/crash.txt)

### Steps to reproduce the issue

Place down an element that uses a unit list (moveunit, unitsequence, unitsequencetrigger etc)
Try to open the unit list
Crash

**Comment by Makowo** [comment]
Fixed with f081560dcf784504725044aff9808f86b948332e
